<?php

use Illuminate\Database\Seeder;
use App\Product;

class ProductsTableDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Product::create(
            [
                'product_name' => 'Man\'s Yellow Bag',
                'product_for' => 'Man',
                'product_tags' => 'man, boys, bags, yellow, hiking, travelling',
                'product_introduction' => 'Yellow Bag for Boys with leather covering inside and also waterproof',
                'product_features' => 'Yellow Bag for Boys with leather covering inside and also waterproof. Yellow Bag for Boys with leather covering inside and also waterproof',
                'product_amount' => 700,
                'product_previous_amount' => 900,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 900,
                'product_main_image' => '0_product-1.jpg',
                'product_description_image' => '0_product-1.jpg',
                'product_sub_image_1' => '0_product-1.jpg',
                'product_sub_image_2' => '0_product-1.jpg',
                'product_sub_image_3' => '0_product-1.jpg',
                'product_sub_image_4' => '0_product-1.jpg',
                'product_sub_image_5' => '0_product-1.jpg',
                'product_sub_image_6' => '0_product-1.jpg',
                'product_stock' => 20,
                'product_weight' => 1,
                'product_colors' => 'Yellow and Black',
                'product_size' => 'Large',
                'vendor_id' => 1,
            ]
        );
        Product::create(
            [
                'product_name' => 'Yellow Sneakers',
                'product_for' => 'All',
                'product_tags' => 'man, boys, girls,  sneakers, shoes, yellow, sports, casual',
                'product_introduction' => 'Yellow Sneakers for Boys and Girls easy to wash and comfortable available UK size 6',
                'product_features' => 'Yellow Sneakers for Boys and Girls easy to wash and comfortable available UK size 6. Yellow Sneakers for Boys and Girls easy to wash and comfortable available UK size 6',
                'product_amount' => 400,
                'product_previous_amount' => 500,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 500,
                'product_main_image' => '0_product-2.jpg',
                'product_description_image' => '0_product-2.jpg',
                'product_sub_image_1' => '0_product-2.jpg',
                'product_sub_image_2' => '0_product-2.jpg',
                'product_sub_image_3' => '0_product-2.jpg',
                'product_sub_image_4' => '0_product-2.jpg',
                'product_sub_image_5' => '0_product-2.jpg',
                'product_sub_image_6' => '0_product-2.jpg',
                'product_stock' => 33,
                'product_weight' => 0.5,
                'product_colors' => 'Yellow',
                'product_size' => '10',
                'vendor_id' => 3,
            ]
        );
        Product::create(
            [
                'product_name' => 'Brown Hoodies for Men',
                'product_for' => 'Man',
                'product_tags' => 'man, boys, hoodies, brownhoodies, brown, casual, winterlook',
                'product_introduction' => 'Man Brown hoodies available size xxl',
                'product_features' => 'Man Brown hoodies available size xxl. Man Brown hoodies available size xxl',
                'product_amount' => 356,
                'product_previous_amount' => 400,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 400,
                'product_main_image' => '0_product-3.jpg',
                'product_description_image' => '0_product-3.jpg',
                'product_sub_image_1' => '0_product-3.jpg',
                'product_sub_image_2' => '0_product-3.jpg',
                'product_sub_image_3' => '0_product-3.jpg',
                'product_sub_image_4' => '0_product-3.jpg',
                'product_sub_image_5' => '0_product-3.jpg',
                'product_sub_image_6' => '0_product-3.jpg',
                'product_stock' => 24,
                'product_weight' => 1,
                'product_colors' => 'Brown',
                'product_size' => 'XXL',
                'vendor_id' => 5,
            ]
        );
        Product::create(
            [
                'product_name' => 'Brown Denim Shirts',
                'product_for' => 'Man',
                'product_tags' => 'man, boys, DenimShirts, Shirts, casual, winterlook',
                'product_introduction' => 'Man SHirts with Denim essence to makes your winter amazing, available size xxl',
                'product_features' => 'Man SHirts with Denim essence to makes your winter amazing, available size xxl. Man SHirts with Denim essence to makes your winter amazing, available size xxl',
                'product_amount' => 378,
                'product_previous_amount' => 421,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 421,
                'product_main_image' => '0_product-4.jpg',
                'product_description_image' => '0_product-4.jpg',
                'product_sub_image_1' => '0_product-4.jpg',
                'product_sub_image_2' => '0_product-4.jpg',
                'product_sub_image_3' => '0_product-4.jpg',
                'product_sub_image_4' => '0_product-4.jpg',
                'product_sub_image_5' => '0_product-4.jpg',
                'product_sub_image_6' => '0_product-4.jpg',
                'product_stock' => 11,
                'product_weight' => 1,
                'product_colors' => 'Brown and Denim',
                'product_size' => 'XL',
                'vendor_id' => 2,
            ]
        );
        Product::create(
            [
                'product_name' => 'Yellow Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, yellow, top, yellowdresses, summerdresses, summerlook',
                'product_introduction' => 'Yellow Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Yellow Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Yellow Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 196,
                'product_previous_amount' => 250,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 250,
                'product_main_image' => '0_product-5.jpg',
                'product_description_image' => '0_product-5.jpg',
                'product_sub_image_1' => '0_product-5.jpg',
                'product_sub_image_2' => '0_product-5.jpg',
                'product_sub_image_3' => '0_product-5.jpg',
                'product_sub_image_4' => '0_product-5.jpg',
                'product_sub_image_5' => '0_product-5.jpg',
                'product_sub_image_6' => '0_product-5.jpg',
                'product_stock' => 33,
                'product_weight' => 0.8,
                'product_colors' => 'Yellow',
                'product_size' => 'M',
                'vendor_id' => 6,
            ]
        );
        Product::create(
            [
                'product_name' => 'Brown Winter Coats',
                'product_for' => 'All',
                'product_tags' => 'man, woman, boys, girls, ladies, boys, coats, browncoats, brown, blazer, winterlook',
                'product_introduction' => 'Brown Coats,  available size xxl',
                'product_features' => 'Brown Coats,  available size xxl. Brown Coats,  available size xxl',
                'product_amount' => 200,
                'product_previous_amount' => 300,
                'product_amount_with_taxes' => 200,
                'product_previous_amount_with_taxes' => 300,
                'product_main_image' => '0_product-6.jpg',
                'product_description_image' => '0_product-6.jpg',
                'product_sub_image_1' => '0_product-6.jpg',
                'product_sub_image_2' => '0_product-6.jpg',
                'product_sub_image_3' => '0_product-6.jpg',
                'product_sub_image_4' => '0_product-6.jpg',
                'product_sub_image_5' => '0_product-6.jpg',
                'product_sub_image_6' => '0_product-6.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Brown',
                'product_size' => 'XL',
                'vendor_id' => 7,
            ]
        );
        Product::create(
            [
                'product_name' => 'Cream Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, creamtop, cream, summertops, summerdresses',
                'product_introduction' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 300,
                'product_previous_amount' => 498,
                'product_amount_with_taxes' => 300,
                'product_previous_amount_with_taxes' => 498,
                'product_main_image' => '0_product-7.jpg',
                'product_description_image' => '0_product-7.jpg',
                'product_sub_image_1' => '0_product-7.jpg',
                'product_sub_image_2' => '0_product-7.jpg',
                'product_sub_image_3' => '0_product-7.jpg',
                'product_sub_image_4' => '0_product-7.jpg',
                'product_sub_image_5' => '0_product-7.jpg',
                'product_sub_image_6' => '0_product-7.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Cream',
                'product_size' => 'M',
                'vendor_id' => 4,
            ]
        );
        Product::create(
            [
                'product_name' => 'Green Shade Wide Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, girls, ladies, coats, green, loosetops',
                'product_introduction' => 'Green Shade wide loose Top for ladies to flaunt their casula looks in this summer',
                'product_features' => 'Green Shade wide loose Top for ladies to flaunt their casula looks in this summer. Green Shade wide loose Top for ladies to flaunt their casula looks in this summer',
                'product_amount' => 250,
                'product_previous_amount' => 375,
                'product_amount_with_taxes' => 250,
                'product_previous_amount_with_taxes' => 375,
                'product_main_image' => '0_product-8.jpg',
                'product_description_image' => '0_product-8.jpg',
                'product_sub_image_1' => '0_product-8.jpg',
                'product_sub_image_2' => '0_product-8.jpg',
                'product_sub_image_3' => '0_product-8.jpg',
                'product_sub_image_4' => '0_product-8.jpg',
                'product_sub_image_5' => '0_product-8.jpg',
                'product_sub_image_6' => '0_product-8.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Green',
                'product_size' => 'XXL',
                'vendor_id' => 7,
            ]
        );
        Product::create(
            [
                'product_name' => 'Black Scarf',
                'product_for' => 'All',
                'product_tags' => 'man, woman, boys, girls, ladies, boys, scarf, blackscarf, blackmuffler, winterlook, winters',
                'product_introduction' => 'Ethnic Black scarfs for all to make your appearance appealing',
                'product_features' => 'Ethnic Black scarfs for all to make your appearance appealing. Ethnic Black scarfs for all to make your appearance appealing',
                'product_amount' => 200,
                'product_previous_amount' => 300,
                'product_amount_with_taxes' => 200,
                'product_previous_amount_with_taxes' => 300,
                'product_main_image' => '0_product-9.jpg',
                'product_description_image' => '0_product-9.jpg',
                'product_sub_image_1' => '0_product-9.jpg',
                'product_sub_image_2' => '0_product-9.jpg',
                'product_sub_image_3' => '0_product-9.jpg',
                'product_sub_image_4' => '0_product-9.jpg',
                'product_sub_image_5' => '0_product-9.jpg',
                'product_sub_image_6' => '0_product-9.jpg',
                'product_stock' => 23,
                'product_weight' => 0.8,
                'product_colors' => 'Black',
                'product_size' => 'Normal',
                'vendor_id' => 6,
            ]
        );
        Product::create(
            [
                'product_name' => 'Yellow Cap',
                'product_for' => 'Woman',
                'product_tags' => 'woman, girls, ladies, caps, yellowcaps,summerlook, summers',
                'product_introduction' => 'Yellow Cap to enhance your this summer with your casual looks',
                'product_features' => 'Yellow Cap to enhance your this summer with your casual looks. Yellow Cap to enhance your this summer with your casual looks',
                'product_amount' => 400,
                'product_previous_amount' => 500,
                'product_amount_with_taxes' => 400,
                'product_previous_amount_with_taxes' => 500,
                'product_main_image' => '0_product-10.jpg',
                'product_description_image' => '0_product-10.jpg',
                'product_sub_image_1' => '0_product-10.jpg',
                'product_sub_image_2' => '0_product-10.jpg',
                'product_sub_image_3' => '0_product-10.jpg',
                'product_sub_image_4' => '0_product-10.jpg',
                'product_sub_image_5' => '0_product-10.jpg',
                'product_sub_image_6' => '0_product-10.jpg',
                'product_stock' => 40,
                'product_weight' => 0.5,
                'product_colors' => 'Yellow',
                'product_size' => 'M',
                'vendor_id' => 2,
            ]
        );
        Product::create(
            [
                'product_name' => 'Grey Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, greytop, grey, summertops, summerdresses',
                'product_introduction' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 200,
                'product_previous_amount' => 300,
                'product_amount_with_taxes' => 200,
                'product_previous_amount_with_taxes' => 300,
                'product_main_image' => '0_product-11.jpg',
                'product_description_image' => '0_product-11.jpg',
                'product_sub_image_1' => '0_product-11.jpg',
                'product_sub_image_2' => '0_product-11.jpg',
                'product_sub_image_3' => '0_product-11.jpg',
                'product_sub_image_4' => '0_product-11.jpg',
                'product_sub_image_5' => '0_product-11.jpg',
                'product_sub_image_6' => '0_product-11.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Grey',
                'product_size' => 'M',
                'vendor_id' => 1,
            ]
        );
        Product::create(
            [
                'product_name' => 'Thin Full Sleeve Sweater Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, sweater, orange, white, cream, wintertops, winterdresses, casuallooks',
                'product_introduction' => 'Thin Full Sleeve Sweater Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Thin Full Sleeve Sweater Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Thin Full Sleeve Sweater Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 300,
                'product_previous_amount' => 350,
                'product_amount_with_taxes' => 300,
                'product_previous_amount_with_taxes' => 350,
                'product_main_image' => '0_product-12.jpg',
                'product_description_image' => '0_product-12.jpg',
                'product_sub_image_1' => '0_product-12.jpg',
                'product_sub_image_2' => '0_product-12.jpg',
                'product_sub_image_3' => '0_product-12.jpg',
                'product_sub_image_4' => '0_product-12.jpg',
                'product_sub_image_5' => '0_product-12.jpg',
                'product_sub_image_6' => '0_product-12.jpg',
                'product_stock' => 28,
                'product_weight' => 1.3,
                'product_colors' => 'Cream, White',
                'product_size' => 'XL',
                'vendor_id' => 3,
            ]
        );
        Product::create(
            [
                'product_name' => 'White Ladies Purse',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, accessories, purse, bag, wallet, womanpurse, white, brownleather, partypurse, partyaccessories',
                'product_introduction' => 'Leather White purse with brown borders to make your party look amazing',
                'product_features' => 'Leather White purse with brown borders to make your party look amazing. Leather White purse with brown borders to make your party look amazing',
                'product_amount' => 400,
                'product_previous_amount' => 500,
                'product_amount_with_taxes' => 400,
                'product_previous_amount_with_taxes' => 500,
                'product_main_image' => '0_product-13.jpg',
                'product_description_image' => '0_product-13.jpg',
                'product_sub_image_1' => '0_product-13.jpg',
                'product_sub_image_2' => '0_product-13.jpg',
                'product_sub_image_3' => '0_product-13.jpg',
                'product_sub_image_4' => '0_product-13.jpg',
                'product_sub_image_5' => '0_product-13.jpg',
                'product_sub_image_6' => '0_product-13.jpg',
                'product_stock' => 20,
                'product_weight' => 0.7,
                'product_colors' => 'White and Golden',
                'product_size' => 'M',
                'vendor_id' => 3,
            ]
        );

        Product::create(
            [
                'product_name' => 'Man\'s Yellow Bag',
                'product_for' => 'Man',
                'product_tags' => 'man, boys, bags, yellow, hiking, travelling',
                'product_introduction' => 'Yellow Bag for Boys with leather covering inside and also waterproof',
                'product_features' => 'Yellow Bag for Boys with leather covering inside and also waterproof. Yellow Bag for Boys with leather covering inside and also waterproof',
                'product_amount' => 700,
                'product_previous_amount' => 900,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 900,
                'product_main_image' => '0_product-1.jpg',
                'product_description_image' => '0_product-1.jpg',
                'product_sub_image_1' => '0_product-1.jpg',
                'product_sub_image_2' => '0_product-1.jpg',
                'product_sub_image_3' => '0_product-1.jpg',
                'product_sub_image_4' => '0_product-1.jpg',
                'product_sub_image_5' => '0_product-1.jpg',
                'product_sub_image_6' => '0_product-1.jpg',
                'product_stock' => 20,
                'product_weight' => 1,
                'product_colors' => 'Yellow and Black',
                'product_size' => 'Large',
                'vendor_id' => 1,
            ]
        );
        Product::create(
            [
                'product_name' => 'Yellow Sneakers',
                'product_for' => 'All',
                'product_tags' => 'man, boys, girls,  sneakers, shoes, yellow, sports, casual',
                'product_introduction' => 'Yellow Sneakers for Boys and Girls easy to wash and comfortable available UK size 6',
                'product_features' => 'Yellow Sneakers for Boys and Girls easy to wash and comfortable available UK size 6. Yellow Sneakers for Boys and Girls easy to wash and comfortable available UK size 6',
                'product_amount' => 400,
                'product_previous_amount' => 500,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 500,
                'product_main_image' => '0_product-2.jpg',
                'product_description_image' => '0_product-2.jpg',
                'product_sub_image_1' => '0_product-2.jpg',
                'product_sub_image_2' => '0_product-2.jpg',
                'product_sub_image_3' => '0_product-2.jpg',
                'product_sub_image_4' => '0_product-2.jpg',
                'product_sub_image_5' => '0_product-2.jpg',
                'product_sub_image_6' => '0_product-2.jpg',
                'product_stock' => 33,
                'product_weight' => 0.5,
                'product_colors' => 'Yellow',
                'product_size' => '10',
                'vendor_id' => 3,
            ]
        );
        Product::create(
            [
                'product_name' => 'Brown Hoodies for Men',
                'product_for' => 'Man',
                'product_tags' => 'man, boys, hoodies, brownhoodies, brown, casual, winterlook',
                'product_introduction' => 'Man Brown hoodies available size xxl',
                'product_features' => 'Man Brown hoodies available size xxl. Man Brown hoodies available size xxl',
                'product_amount' => 356,
                'product_previous_amount' => 400,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 400,
                'product_main_image' => '0_product-3.jpg',
                'product_description_image' => '0_product-3.jpg',
                'product_sub_image_1' => '0_product-3.jpg',
                'product_sub_image_2' => '0_product-3.jpg',
                'product_sub_image_3' => '0_product-3.jpg',
                'product_sub_image_4' => '0_product-3.jpg',
                'product_sub_image_5' => '0_product-3.jpg',
                'product_sub_image_6' => '0_product-3.jpg',
                'product_stock' => 24,
                'product_weight' => 1,
                'product_colors' => 'Brown',
                'product_size' => 'XXL',
                'vendor_id' => 5,
            ]
        );
        Product::create(
            [
                'product_name' => 'Brown Denim Shirts',
                'product_for' => 'Man',
                'product_tags' => 'man, boys, DenimShirts, Shirts, casual, winterlook',
                'product_introduction' => 'Man SHirts with Denim essence to makes your winter amazing, available size xxl',
                'product_features' => 'Man SHirts with Denim essence to makes your winter amazing, available size xxl. Man SHirts with Denim essence to makes your winter amazing, available size xxl',
                'product_amount' => 378,
                'product_previous_amount' => 421,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 421,
                'product_main_image' => '0_product-4.jpg',
                'product_description_image' => '0_product-4.jpg',
                'product_sub_image_1' => '0_product-4.jpg',
                'product_sub_image_2' => '0_product-4.jpg',
                'product_sub_image_3' => '0_product-4.jpg',
                'product_sub_image_4' => '0_product-4.jpg',
                'product_sub_image_5' => '0_product-4.jpg',
                'product_sub_image_6' => '0_product-4.jpg',
                'product_stock' => 11,
                'product_weight' => 1,
                'product_colors' => 'Brown and Denim',
                'product_size' => 'XL',
                'vendor_id' => 2,
            ]
        );
        Product::create(
            [
                'product_name' => 'Yellow Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, yellow, top, yellowdresses, summerdresses, summerlook',
                'product_introduction' => 'Yellow Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Yellow Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Yellow Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 196,
                'product_previous_amount' => 250,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 250,
                'product_main_image' => '0_product-5.jpg',
                'product_description_image' => '0_product-5.jpg',
                'product_sub_image_1' => '0_product-5.jpg',
                'product_sub_image_2' => '0_product-5.jpg',
                'product_sub_image_3' => '0_product-5.jpg',
                'product_sub_image_4' => '0_product-5.jpg',
                'product_sub_image_5' => '0_product-5.jpg',
                'product_sub_image_6' => '0_product-5.jpg',
                'product_stock' => 33,
                'product_weight' => 0.8,
                'product_colors' => 'Yellow',
                'product_size' => 'M',
                'vendor_id' => 6,
            ]
        );
        Product::create(
            [
                'product_name' => 'Brown Winter Coats',
                'product_for' => 'All',
                'product_tags' => 'man, woman, boys, girls, ladies, boys, coats, browncoats, brown, blazer, winterlook',
                'product_introduction' => 'Brown Coats,  available size xxl',
                'product_features' => 'Brown Coats,  available size xxl. Brown Coats,  available size xxl',
                'product_amount' => 200,
                'product_previous_amount' => 300,
                'product_amount_with_taxes' => 200,
                'product_previous_amount_with_taxes' => 300,
                'product_main_image' => '0_product-6.jpg',
                'product_description_image' => '0_product-6.jpg',
                'product_sub_image_1' => '0_product-6.jpg',
                'product_sub_image_2' => '0_product-6.jpg',
                'product_sub_image_3' => '0_product-6.jpg',
                'product_sub_image_4' => '0_product-6.jpg',
                'product_sub_image_5' => '0_product-6.jpg',
                'product_sub_image_6' => '0_product-6.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Brown',
                'product_size' => 'XL',
                'vendor_id' => 7,
            ]
        );
        Product::create(
            [
                'product_name' => 'Cream Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, creamtop, cream, summertops, summerdresses',
                'product_introduction' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 300,
                'product_previous_amount' => 498,
                'product_amount_with_taxes' => 300,
                'product_previous_amount_with_taxes' => 498,
                'product_main_image' => '0_product-7.jpg',
                'product_description_image' => '0_product-7.jpg',
                'product_sub_image_1' => '0_product-7.jpg',
                'product_sub_image_2' => '0_product-7.jpg',
                'product_sub_image_3' => '0_product-7.jpg',
                'product_sub_image_4' => '0_product-7.jpg',
                'product_sub_image_5' => '0_product-7.jpg',
                'product_sub_image_6' => '0_product-7.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Cream',
                'product_size' => 'M',
                'vendor_id' => 4,
            ]
        );
        Product::create(
            [
                'product_name' => 'Green Shade Wide Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, girls, ladies, coats, green, loosetops',
                'product_introduction' => 'Green Shade wide loose Top for ladies to flaunt their casula looks in this summer',
                'product_features' => 'Green Shade wide loose Top for ladies to flaunt their casula looks in this summer. Green Shade wide loose Top for ladies to flaunt their casula looks in this summer',
                'product_amount' => 250,
                'product_previous_amount' => 375,
                'product_amount_with_taxes' => 250,
                'product_previous_amount_with_taxes' => 375,
                'product_main_image' => '0_product-8.jpg',
                'product_description_image' => '0_product-8.jpg',
                'product_sub_image_1' => '0_product-8.jpg',
                'product_sub_image_2' => '0_product-8.jpg',
                'product_sub_image_3' => '0_product-8.jpg',
                'product_sub_image_4' => '0_product-8.jpg',
                'product_sub_image_5' => '0_product-8.jpg',
                'product_sub_image_6' => '0_product-8.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Green',
                'product_size' => 'XXL',
                'vendor_id' => 7,
            ]
        );
        Product::create(
            [
                'product_name' => 'Black Scarf',
                'product_for' => 'All',
                'product_tags' => 'man, woman, boys, girls, ladies, boys, scarf, blackscarf, blackmuffler, winterlook, winters',
                'product_introduction' => 'Ethnic Black scarfs for all to make your appearance appealing',
                'product_features' => 'Ethnic Black scarfs for all to make your appearance appealing. Ethnic Black scarfs for all to make your appearance appealing',
                'product_amount' => 200,
                'product_previous_amount' => 300,
                'product_amount_with_taxes' => 200,
                'product_previous_amount_with_taxes' => 300,
                'product_main_image' => '0_product-9.jpg',
                'product_description_image' => '0_product-9.jpg',
                'product_sub_image_1' => '0_product-9.jpg',
                'product_sub_image_2' => '0_product-9.jpg',
                'product_sub_image_3' => '0_product-9.jpg',
                'product_sub_image_4' => '0_product-9.jpg',
                'product_sub_image_5' => '0_product-9.jpg',
                'product_sub_image_6' => '0_product-9.jpg',
                'product_stock' => 23,
                'product_weight' => 0.8,
                'product_colors' => 'Black',
                'product_size' => 'Normal',
                'vendor_id' => 6,
            ]
        );
        Product::create(
            [
                'product_name' => 'Yellow Cap',
                'product_for' => 'Woman',
                'product_tags' => 'woman, girls, ladies, caps, yellowcaps,summerlook, summers',
                'product_introduction' => 'Yellow Cap to enhance your this summer with your casual looks',
                'product_features' => 'Yellow Cap to enhance your this summer with your casual looks. Yellow Cap to enhance your this summer with your casual looks',
                'product_amount' => 400,
                'product_previous_amount' => 500,
                'product_amount_with_taxes' => 400,
                'product_previous_amount_with_taxes' => 500,
                'product_main_image' => '0_product-10.jpg',
                'product_description_image' => '0_product-10.jpg',
                'product_sub_image_1' => '0_product-10.jpg',
                'product_sub_image_2' => '0_product-10.jpg',
                'product_sub_image_3' => '0_product-10.jpg',
                'product_sub_image_4' => '0_product-10.jpg',
                'product_sub_image_5' => '0_product-10.jpg',
                'product_sub_image_6' => '0_product-10.jpg',
                'product_stock' => 40,
                'product_weight' => 0.5,
                'product_colors' => 'Yellow',
                'product_size' => 'M',
                'vendor_id' => 2,
            ]
        );
        Product::create(
            [
                'product_name' => 'Grey Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, greytop, grey, summertops, summerdresses',
                'product_introduction' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 200,
                'product_previous_amount' => 300,
                'product_amount_with_taxes' => 200,
                'product_previous_amount_with_taxes' => 300,
                'product_main_image' => '0_product-11.jpg',
                'product_description_image' => '0_product-11.jpg',
                'product_sub_image_1' => '0_product-11.jpg',
                'product_sub_image_2' => '0_product-11.jpg',
                'product_sub_image_3' => '0_product-11.jpg',
                'product_sub_image_4' => '0_product-11.jpg',
                'product_sub_image_5' => '0_product-11.jpg',
                'product_sub_image_6' => '0_product-11.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Grey',
                'product_size' => 'M',
                'vendor_id' => 1,
            ]
        );
        Product::create(
            [
                'product_name' => 'Thin Full Sleeve Sweater Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, sweater, orange, white, cream, wintertops, winterdresses, casuallooks',
                'product_introduction' => 'Thin Full Sleeve Sweater Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Thin Full Sleeve Sweater Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Thin Full Sleeve Sweater Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 300,
                'product_previous_amount' => 350,
                'product_amount_with_taxes' => 300,
                'product_previous_amount_with_taxes' => 350,
                'product_main_image' => '0_product-12.jpg',
                'product_description_image' => '0_product-12.jpg',
                'product_sub_image_1' => '0_product-12.jpg',
                'product_sub_image_2' => '0_product-12.jpg',
                'product_sub_image_3' => '0_product-12.jpg',
                'product_sub_image_4' => '0_product-12.jpg',
                'product_sub_image_5' => '0_product-12.jpg',
                'product_sub_image_6' => '0_product-12.jpg',
                'product_stock' => 28,
                'product_weight' => 1.3,
                'product_colors' => 'Cream, White',
                'product_size' => 'XL',
                'vendor_id' => 3,
            ]
        );
        Product::create(
            [
                'product_name' => 'White Ladies Purse',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, accessories, purse, bag, wallet, womanpurse, white, brownleather, partypurse, partyaccessories',
                'product_introduction' => 'Leather White purse with brown borders to make your party look amazing',
                'product_features' => 'Leather White purse with brown borders to make your party look amazing. Leather White purse with brown borders to make your party look amazing',
                'product_amount' => 400,
                'product_previous_amount' => 500,
                'product_amount_with_taxes' => 400,
                'product_previous_amount_with_taxes' => 500,
                'product_main_image' => '0_product-13.jpg',
                'product_description_image' => '0_product-13.jpg',
                'product_sub_image_1' => '0_product-13.jpg',
                'product_sub_image_2' => '0_product-13.jpg',
                'product_sub_image_3' => '0_product-13.jpg',
                'product_sub_image_4' => '0_product-13.jpg',
                'product_sub_image_5' => '0_product-13.jpg',
                'product_sub_image_6' => '0_product-13.jpg',
                'product_stock' => 20,
                'product_weight' => 0.7,
                'product_colors' => 'White and Golden',
                'product_size' => 'M',
                'vendor_id' => 3,
            ]
        );

        Product::create(
            [
                'product_name' => 'Man\'s Yellow Bag',
                'product_for' => 'Man',
                'product_tags' => 'man, boys, bags, yellow, hiking, travelling',
                'product_introduction' => 'Yellow Bag for Boys with leather covering inside and also waterproof',
                'product_features' => 'Yellow Bag for Boys with leather covering inside and also waterproof. Yellow Bag for Boys with leather covering inside and also waterproof',
                'product_amount' => 700,
                'product_previous_amount' => 900,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 900,
                'product_main_image' => '0_product-1.jpg',
                'product_description_image' => '0_product-1.jpg',
                'product_sub_image_1' => '0_product-1.jpg',
                'product_sub_image_2' => '0_product-1.jpg',
                'product_sub_image_3' => '0_product-1.jpg',
                'product_sub_image_4' => '0_product-1.jpg',
                'product_sub_image_5' => '0_product-1.jpg',
                'product_sub_image_6' => '0_product-1.jpg',
                'product_stock' => 20,
                'product_weight' => 1,
                'product_colors' => 'Yellow and Black',
                'product_size' => 'Large',
                'vendor_id' => 1,
            ]
        );
        Product::create(
            [
                'product_name' => 'Yellow Sneakers',
                'product_for' => 'All',
                'product_tags' => 'man, boys, girls,  sneakers, shoes, yellow, sports, casual',
                'product_introduction' => 'Yellow Sneakers for Boys and Girls easy to wash and comfortable available UK size 6',
                'product_features' => 'Yellow Sneakers for Boys and Girls easy to wash and comfortable available UK size 6. Yellow Sneakers for Boys and Girls easy to wash and comfortable available UK size 6',
                'product_amount' => 400,
                'product_previous_amount' => 500,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 500,
                'product_main_image' => '0_product-2.jpg',
                'product_description_image' => '0_product-2.jpg',
                'product_sub_image_1' => '0_product-2.jpg',
                'product_sub_image_2' => '0_product-2.jpg',
                'product_sub_image_3' => '0_product-2.jpg',
                'product_sub_image_4' => '0_product-2.jpg',
                'product_sub_image_5' => '0_product-2.jpg',
                'product_sub_image_6' => '0_product-2.jpg',
                'product_stock' => 33,
                'product_weight' => 0.5,
                'product_colors' => 'Yellow',
                'product_size' => '10',
                'vendor_id' => 3,
            ]
        );
        Product::create(
            [
                'product_name' => 'Brown Hoodies for Men',
                'product_for' => 'Man',
                'product_tags' => 'man, boys, hoodies, brownhoodies, brown, casual, winterlook',
                'product_introduction' => 'Man Brown hoodies available size xxl',
                'product_features' => 'Man Brown hoodies available size xxl. Man Brown hoodies available size xxl',
                'product_amount' => 356,
                'product_previous_amount' => 400,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 400,
                'product_main_image' => '0_product-3.jpg',
                'product_description_image' => '0_product-3.jpg',
                'product_sub_image_1' => '0_product-3.jpg',
                'product_sub_image_2' => '0_product-3.jpg',
                'product_sub_image_3' => '0_product-3.jpg',
                'product_sub_image_4' => '0_product-3.jpg',
                'product_sub_image_5' => '0_product-3.jpg',
                'product_sub_image_6' => '0_product-3.jpg',
                'product_stock' => 24,
                'product_weight' => 1,
                'product_colors' => 'Brown',
                'product_size' => 'XXL',
                'vendor_id' => 5,
            ]
        );
        Product::create(
            [
                'product_name' => 'Brown Denim Shirts',
                'product_for' => 'Man',
                'product_tags' => 'man, boys, DenimShirts, Shirts, casual, winterlook',
                'product_introduction' => 'Man SHirts with Denim essence to makes your winter amazing, available size xxl',
                'product_features' => 'Man SHirts with Denim essence to makes your winter amazing, available size xxl. Man SHirts with Denim essence to makes your winter amazing, available size xxl',
                'product_amount' => 378,
                'product_previous_amount' => 421,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 421,
                'product_main_image' => '0_product-4.jpg',
                'product_description_image' => '0_product-4.jpg',
                'product_sub_image_1' => '0_product-4.jpg',
                'product_sub_image_2' => '0_product-4.jpg',
                'product_sub_image_3' => '0_product-4.jpg',
                'product_sub_image_4' => '0_product-4.jpg',
                'product_sub_image_5' => '0_product-4.jpg',
                'product_sub_image_6' => '0_product-4.jpg',
                'product_stock' => 11,
                'product_weight' => 1,
                'product_colors' => 'Brown and Denim',
                'product_size' => 'XL',
                'vendor_id' => 2,
            ]
        );
        Product::create(
            [
                'product_name' => 'Yellow Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, yellow, top, yellowdresses, summerdresses, summerlook',
                'product_introduction' => 'Yellow Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Yellow Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Yellow Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 196,
                'product_previous_amount' => 250,
                'product_amount_with_taxes' => 700,
                'product_previous_amount_with_taxes' => 250,
                'product_main_image' => '0_product-5.jpg',
                'product_description_image' => '0_product-5.jpg',
                'product_sub_image_1' => '0_product-5.jpg',
                'product_sub_image_2' => '0_product-5.jpg',
                'product_sub_image_3' => '0_product-5.jpg',
                'product_sub_image_4' => '0_product-5.jpg',
                'product_sub_image_5' => '0_product-5.jpg',
                'product_sub_image_6' => '0_product-5.jpg',
                'product_stock' => 33,
                'product_weight' => 0.8,
                'product_colors' => 'Yellow',
                'product_size' => 'M',
                'vendor_id' => 6,
            ]
        );
        Product::create(
            [
                'product_name' => 'Brown Winter Coats',
                'product_for' => 'All',
                'product_tags' => 'man, woman, boys, girls, ladies, boys, coats, browncoats, brown, blazer, winterlook',
                'product_introduction' => 'Brown Coats,  available size xxl',
                'product_features' => 'Brown Coats,  available size xxl. Brown Coats,  available size xxl',
                'product_amount' => 200,
                'product_previous_amount' => 300,
                'product_amount_with_taxes' => 200,
                'product_previous_amount_with_taxes' => 300,
                'product_main_image' => '0_product-6.jpg',
                'product_description_image' => '0_product-6.jpg',
                'product_sub_image_1' => '0_product-6.jpg',
                'product_sub_image_2' => '0_product-6.jpg',
                'product_sub_image_3' => '0_product-6.jpg',
                'product_sub_image_4' => '0_product-6.jpg',
                'product_sub_image_5' => '0_product-6.jpg',
                'product_sub_image_6' => '0_product-6.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Brown',
                'product_size' => 'XL',
                'vendor_id' => 7,
            ]
        );
        Product::create(
            [
                'product_name' => 'Cream Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, creamtop, cream, summertops, summerdresses',
                'product_introduction' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 300,
                'product_previous_amount' => 498,
                'product_amount_with_taxes' => 300,
                'product_previous_amount_with_taxes' => 498,
                'product_main_image' => '0_product-7.jpg',
                'product_description_image' => '0_product-7.jpg',
                'product_sub_image_1' => '0_product-7.jpg',
                'product_sub_image_2' => '0_product-7.jpg',
                'product_sub_image_3' => '0_product-7.jpg',
                'product_sub_image_4' => '0_product-7.jpg',
                'product_sub_image_5' => '0_product-7.jpg',
                'product_sub_image_6' => '0_product-7.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Cream',
                'product_size' => 'M',
                'vendor_id' => 4,
            ]
        );
        Product::create(
            [
                'product_name' => 'Green Shade Wide Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, girls, ladies, coats, green, loosetops',
                'product_introduction' => 'Green Shade wide loose Top for ladies to flaunt their casula looks in this summer',
                'product_features' => 'Green Shade wide loose Top for ladies to flaunt their casula looks in this summer. Green Shade wide loose Top for ladies to flaunt their casula looks in this summer',
                'product_amount' => 250,
                'product_previous_amount' => 375,
                'product_amount_with_taxes' => 250,
                'product_previous_amount_with_taxes' => 375,
                'product_main_image' => '0_product-8.jpg',
                'product_description_image' => '0_product-8.jpg',
                'product_sub_image_1' => '0_product-8.jpg',
                'product_sub_image_2' => '0_product-8.jpg',
                'product_sub_image_3' => '0_product-8.jpg',
                'product_sub_image_4' => '0_product-8.jpg',
                'product_sub_image_5' => '0_product-8.jpg',
                'product_sub_image_6' => '0_product-8.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Green',
                'product_size' => 'XXL',
                'vendor_id' => 7,
            ]
        );
        Product::create(
            [
                'product_name' => 'Black Scarf',
                'product_for' => 'All',
                'product_tags' => 'man, woman, boys, girls, ladies, boys, scarf, blackscarf, blackmuffler, winterlook, winters',
                'product_introduction' => 'Ethnic Black scarfs for all to make your appearance appealing',
                'product_features' => 'Ethnic Black scarfs for all to make your appearance appealing. Ethnic Black scarfs for all to make your appearance appealing',
                'product_amount' => 200,
                'product_previous_amount' => 300,
                'product_amount_with_taxes' => 200,
                'product_previous_amount_with_taxes' => 300,
                'product_main_image' => '0_product-9.jpg',
                'product_description_image' => '0_product-9.jpg',
                'product_sub_image_1' => '0_product-9.jpg',
                'product_sub_image_2' => '0_product-9.jpg',
                'product_sub_image_3' => '0_product-9.jpg',
                'product_sub_image_4' => '0_product-9.jpg',
                'product_sub_image_5' => '0_product-9.jpg',
                'product_sub_image_6' => '0_product-9.jpg',
                'product_stock' => 23,
                'product_weight' => 0.8,
                'product_colors' => 'Black',
                'product_size' => 'Normal',
                'vendor_id' => 6,
            ]
        );
        Product::create(
            [
                'product_name' => 'Yellow Cap',
                'product_for' => 'Woman',
                'product_tags' => 'woman, girls, ladies, caps, yellowcaps,summerlook, summers',
                'product_introduction' => 'Yellow Cap to enhance your this summer with your casual looks',
                'product_features' => 'Yellow Cap to enhance your this summer with your casual looks. Yellow Cap to enhance your this summer with your casual looks',
                'product_amount' => 400,
                'product_previous_amount' => 500,
                'product_amount_with_taxes' => 400,
                'product_previous_amount_with_taxes' => 500,
                'product_main_image' => '0_product-10.jpg',
                'product_description_image' => '0_product-10.jpg',
                'product_sub_image_1' => '0_product-10.jpg',
                'product_sub_image_2' => '0_product-10.jpg',
                'product_sub_image_3' => '0_product-10.jpg',
                'product_sub_image_4' => '0_product-10.jpg',
                'product_sub_image_5' => '0_product-10.jpg',
                'product_sub_image_6' => '0_product-10.jpg',
                'product_stock' => 40,
                'product_weight' => 0.5,
                'product_colors' => 'Yellow',
                'product_size' => 'M',
                'vendor_id' => 2,
            ]
        );
        Product::create(
            [
                'product_name' => 'Grey Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, greytop, grey, summertops, summerdresses',
                'product_introduction' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Cream Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 200,
                'product_previous_amount' => 300,
                'product_amount_with_taxes' => 200,
                'product_previous_amount_with_taxes' => 300,
                'product_main_image' => '0_product-11.jpg',
                'product_description_image' => '0_product-11.jpg',
                'product_sub_image_1' => '0_product-11.jpg',
                'product_sub_image_2' => '0_product-11.jpg',
                'product_sub_image_3' => '0_product-11.jpg',
                'product_sub_image_4' => '0_product-11.jpg',
                'product_sub_image_5' => '0_product-11.jpg',
                'product_sub_image_6' => '0_product-11.jpg',
                'product_stock' => 33,
                'product_weight' => 1,
                'product_colors' => 'Grey',
                'product_size' => 'M',
                'vendor_id' => 1,
            ]
        );
        Product::create(
            [
                'product_name' => 'Thin Full Sleeve Sweater Top',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, sweater, orange, white, cream, wintertops, winterdresses, casuallooks',
                'product_introduction' => 'Thin Full Sleeve Sweater Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_features' => 'Thin Full Sleeve Sweater Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl. Thin Full Sleeve Sweater Top for ladies to flaunt their looks in this summer, available in size xl, xxl, xxxl',
                'product_amount' => 300,
                'product_previous_amount' => 350,
                'product_amount_with_taxes' => 300,
                'product_previous_amount_with_taxes' => 350,
                'product_main_image' => '0_product-12.jpg',
                'product_description_image' => '0_product-12.jpg',
                'product_sub_image_1' => '0_product-12.jpg',
                'product_sub_image_2' => '0_product-12.jpg',
                'product_sub_image_3' => '0_product-12.jpg',
                'product_sub_image_4' => '0_product-12.jpg',
                'product_sub_image_5' => '0_product-12.jpg',
                'product_sub_image_6' => '0_product-12.jpg',
                'product_stock' => 28,
                'product_weight' => 1.3,
                'product_colors' => 'Cream, White',
                'product_size' => 'XL',
                'vendor_id' => 3,
            ]
        );
        Product::create(
            [
                'product_name' => 'White Ladies Purse',
                'product_for' => 'Woman',
                'product_tags' => 'woman, ladies, girls, accessories, purse, bag, wallet, womanpurse, white, brownleather, partypurse, partyaccessories',
                'product_introduction' => 'Leather White purse with brown borders to make your party look amazing',
                'product_features' => 'Leather White purse with brown borders to make your party look amazing. Leather White purse with brown borders to make your party look amazing',
                'product_amount' => 400,
                'product_previous_amount' => 500,
                'product_amount_with_taxes' => 400,
                'product_previous_amount_with_taxes' => 500,
                'product_main_image' => '0_product-13.jpg',
                'product_description_image' => '0_product-13.jpg',
                'product_sub_image_1' => '0_product-13.jpg',
                'product_sub_image_2' => '0_product-13.jpg',
                'product_sub_image_3' => '0_product-13.jpg',
                'product_sub_image_4' => '0_product-13.jpg',
                'product_sub_image_5' => '0_product-13.jpg',
                'product_sub_image_6' => '0_product-13.jpg',
                'product_stock' => 20,
                'product_weight' => 0.7,
                'product_colors' => 'White and Golden',
                'product_size' => 'M',
                'vendor_id' => 3,
            ]
        );
    }
}
